### ISSUE TITLE
Feat: 검색 기본 api 구현

### ISSUE THREAD

**Issue by sohyun-99** [ForUs-KW/NaviForYou_Backend#17]
## 📌 Feature Issue
검색 기본 api 구현

## 📝 To-do
- [x]  키워드로 검색 api 구현
- [x] 네이버 지역 api 사용 -> parsing
- [x] 현위치와의 거리 계산 로직 추가
- [x] 그외 예외처리 진행

## ETC
> 추가 논의 및 작업 필요
