### ISSUE TITLE
Feat : Security , Swagger 기본 세팅

### ISSUE THREAD

**Issue by sohyun-99** [ForUs-KW/NaviForYou_Backend#3]
## 📌 Feature Issue
Security , Swagger 기본 세팅 구성 완료

## 📝 To-do
- [x] SecurityConfig 파일 생성
- [x] SwaggerConfig 파일 생성
- [x] build.gradle 수정

## ETC
- 스프링부트 버전 3 -> 2.7로 다운그레이드
>
