### ISSUE TITLE
Feat: 사용자 설정 장애인 편의 시설

### ISSUE THREAD

**Issue by ckdals4600** [ForUs-KW/NaviForYou_Backend#30]
## 📌 Feature Issue
- 건물 정보에 표기된 장애인 편의시설을 사용자가 추가/삭제 할 수 있도록 기능 추가
- 일정 수 도달 시 디비에 저장하여 전체 데이터에 반영

## 📝 To-do
- [x] 편의시설 추가/삭제 
- [x] 일정 수 도달 시 디비에 저장
- [x] 장애인 편의시설 정보 제공시 디비 데이터 반영
- [x] 수정 페이지 이동 시 장애인 편의시설 정보 제공
   - [x] redis에 현재 보고 있는 건물에 대한 장애인 편의 시설 정보 저장

## ETC
> 건물 정보에 나오도록 코드 리펙토링 필요
> redis 이용으로 공공데이터 접근 최소화 필요
