### ISSUE TITLE
Refactor : 길찾기 코드 리펙토링

### ISSUE THREAD

**Issue by sohyun-99** [ForUs-KW/NaviForYou_Backend#41]
## 📌 Feature Issue
길찾기 코드 리펙토링

## 📝 To-do
- [x] 저상버스 일반버스 구분
- [x] 저상버스 선택 시 -> 일반버스의 루트 삭제
- [x] string 좌표 input 통일
- [x] 코드 정리

## ETC
>
